services:

  app:
    build: .
    ports:
      - 8090:80
    volumes:
      - ./app:/app

  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      - PMA_ARBITRARY=1